language: php
php:
  - '7.0'
before_script:
  - composer update --prefer-dist --prefer-stable
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
branches:
  only:
  - master
  - develop
cache:
  directories:
    - $HOME/.composer/cache
