language: php
php:
  - '7.0'
  - '7.1'
env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
before_script:
  - composer update --prefer-dist $PREFER_LOWEST
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
branches:
  only:
  - master
  - develop
cache:
  directories:
    - $HOME/.composer/cache
